### ISSUE TITLE
Updating product row during checkout with AzureLocalCarts doesn't trigger total calculations

### ISSUE THREAD

**Issue by davidmcatee-azure** [azurestandard/azure-angular-providers#43]
From https://github.com/azurestandard/website/issues/307.

**Comment by wking** [comment]
This is using the code from #41?

**Comment by davidmcatee-azure** [comment]
AzureLocalCarts doesn't use the code from #41. It needs to calculate the totals after the user changes the quantity of an order line. PR coming.
