### ISSUE TITLE
Don't default to post-cutoff orders (when there are other choices available?)

### ISSUE THREAD

**Issue by wking** [azurestandard/azure-angular-providers#55]
In today's software meeting David Stelzer pointed out problems he was having with his customer account, where the existence of a placed order (for a trip that cutoff in 2013) was being selected as his working order.  In order to shop, he had to explicitly visit his [drop list](https://website.azurestandard.com/#/my-account/drops) and click “shop”.

Our order-bumping logic is more robust now, but we may want [`shouldSetCart`](https://github.com/azurestandard/azure-angular-providers/blob/v0.8.4/azure-providers.js#L969-L991) to ignore placed, post-cutoff orders (so a customer without pre-cutoff orders would not have a default working order at all, even if they had placed post-cutoff orders).  That means folks have to [click “shop”](https://website.azurestandard.com/#/my-account/drops) in cases where they do want to manipulate a placed, post-cutoff order (e.g. they are customer-service or got a short-drop email).

On the other hand, we currently don't change your working order at checkout-time or cutoff-time.  So we may still have users working on orders that are sitting in the window between placed and verified/bumped (even if we update the default selection rules here).  We probably want to update the website to be more clear about that situation, regardless of how this issue is resolved.

**Comment by wking** [comment]
This is in the same space as azurestandard/website#483.  I think they're distinct issues, but could be wrong about that.

**Comment by davidmcatee-azure** [comment]
The website no longer uses `AzureCarts` from azure-angular-providers. The "default active order" logic has been moved to [here](https://github.com/azurestandard/website/blob/v0.1.35/app/scripts/services/orders.js#L150-L176).

I will be filing a PR to remove the deprecated services.
