### ISSUE TITLE
Upgrade algoliasearch client to latest version

### ISSUE THREAD

**Issue by davidmcatee-azure** [azurestandard/azure-angular-providers#59]
Also, I don't see why we shouldn't use the [smaller search-only client](https://www.algolia.com/doc/api-client/javascript/getting-started#search-onlylite-client), since that's all we're using it for.

**Comment by MercenaryJosh** [comment]
we are using the angular module and it doesn't appear that the search-only client includes that. https://www.algolia.com/doc/api-client/javascript/getting-started#angularjs-module

**Comment by MercenaryJosh** [comment]
also, for this repo in particular, the dependency in bower.json is `"algoliasearch": "^3.0.0"` which will match the current version 3.18.1 so it does not need to be updated here.

**Comment by davidmcatee-azure** [comment]
> we are using the angular module and it doesn't appear that the search-only client includes that. https://www.algolia.com/doc/api-client/javascript/getting-started#angularjs-module

Hm, it's too bad they don't unbundle the angular part and version it separately.
